push_indications:
  name: 'Передать показания'
  description: 'Передать показания в личный кабинет'
  target:
    entity:
      integration: tns_energo
      device_class: tns_energo_meter
  fields:
    indications:
      name: 'Список показаний'
      description: 'Список показаний (от 1 до 3) для тарифов: T1, T2, T3'
      required: true
      advanced: false
      example: '123, 456, 789'
      selector:
        text:
          multiline: false
    incremental:
      name: 'Сложить известные переданные показания'
      description: 'Сложить известные переданные показания счётчика с передаваемыми'
      required: false
      advanced: false
      default: false
      example: 'false'
      selector:
        boolean:
    notification:
      name: 'Показывать уведомление'
      description: 'Показывать уведомление при успешной передаче'
      required: false
      advanced: false
      default: false
      example: 'true'
      selector:
        boolean:
    ignore_indications:
      name: 'Игнорировать ограничения'
      description: 'Игнорировать ограничения по показаниям'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:

calculate_indications:
  name: 'Подсчитать начисления'
  description: 'Подсчитать начисления по передаваемым показаниям'
  target:
    entity:
      integration: tns_energo
      device_class: tns_energo_meter
  fields:
    indications:
      name: 'Список показаний'
      description: 'Список показаний (от 1 до 3) для тарифов: T1, T2, T3'
      required: true
      advanced: false
      example: '123, 456, 789'
      selector:
        text:
          multiline: false
    incremental:
      name: 'Сложить известные переданные показания'
      description: 'Сложить известные переданные показания счётчика с передаваемыми'
      required: false
      advanced: false
      default: false
      example: 'false'
      selector:
        boolean:
    notification:
      name: 'Показывать уведомление'
      description: 'Показывать уведомление при успешной передаче'
      required: false
      advanced: false
      default: false
      example: 'true'
      selector:
        boolean:
    ignore_indications:
      name: 'Игнорировать ограничения'
      description: 'Игнорировать ограничения по показаниям'
      required: false
      advanced: true
      default: false
      example: 'false'
      selector:
        boolean:


set_description:
  name: "Задать комментарий к лицевому счёту"
  description: "Задать комментарий к лицевому счёту. Пустой параметр `description` (или его упущение) очистит описание к лицевому счёту."
  target:
    entity:
      integration: tns_energo
      device_class: tns_energo_account
  fields:
    description:
      name: 'Описание'
      description: 'Описание'
      required: false
      advanced: false
      selector:
        text:
          multiline: false

get_payments:
  name: "Получить перечень платежей"
  description: "Получить перечень платежей, связанных с лицевым счётом, которые находятся внутри заданного периода"
  target:
    entity:
      integration: tns_energo
      device_class: tns_energo_account
  fields:
    start:
      name: "Начало"
      description: "Дата начала периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false
    end:
      name: "Окончание"
      description: "Дата окончания периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false

get_indications:
  name: "Получить перечень квитанций"
  description: "Получить перечень квитанций, связанных с счётчиком (-ами), которые находятся внутри заданного периода"
  target:
    entity:
      integration: tns_energo
      device_class: tns_energo_meter
  fields:
    start:
      name: "Начало"
      description: "Дата начала периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false
    end:
      name: "Окончание"
      description: "Дата окончания периода"
      required: false
      advanced: false
      selector:
        text:
          multiline: false
    meter_codes:
      name: "Номера счётчиков"
      description: "Номера счётчиков (недоступно при использовании на счётчиках)"
      required: false
      advanced: false
      selector:
        text:
          multiline: true
